### ISSUE TITLE
Installation fails in clean virtualenv

### ISSUE THREAD

**Issue by Xenokrates** [snowformatics/gwas_web_production#1]
The installation fails in a clean Python environment

### Install in virtualenv and run install process

> git clone https://github.com/snowformatics/gwas_web_production.git
> /opt/Bio/python/3.7.7/bin/virtualenv --clear-app-data -p python3.7 gwas_web_production
> cd gwas_web_production/
> source bin/activate
> python -m pip install --upgrade pip
> pip install -r requirements.txt  > >(tee -a stdout.log) 2> >(tee -a stderr.log >&2) 

### Error

> Building wheels for collected packages: fastlmm
> Building wheel for fastlmm (PEP 517): started
> Building wheel for fastlmm (PEP 517): finished with status 'error'
> Failed to build fastlmm

See attached files
[stderr.log](https://github.com/snowformatics/gwas_web_production/files/6669783/stderr.log) &
[stdout.log](https://github.com/snowformatics/gwas_web_production/files/6669785/stdout.log)

Environment: CentOS 7 with a self compiled Python 3.7

Best regards
H.

**Comment by Xenokrates** [comment]
May be this problem should go upstream to the **fastlmm** package maintainers.

It is reproducible for both versions  _0.5.5_ (which you require) & _0.5.9_ (=current).

> virtualenv -p python3.7 install_fastlmm
> cd install_fastlmm
> source bin/activate
> pip install fastlmm==0.5.5

Error (like above):
```
g++ -pthread -shared build/temp.linux-x86_64-3.7/fastlmm/util/matrix/cample.o -Lexternal/intel/linux/mkl/lib/intel64 -Lexternal/intel/linux/compiler/lib/intel64 -Wl,--enable-new-dtags,-Rexternal/intel/linux/mkl/lib/intel64 -Wl,--enable-new-dtags,-Rexternal/intel/linux/compiler/lib/intel64 -lmkl_rt -lmkl_intel_ilp64 -lmkl_core -lmkl_intel_thread -liomp5 -lmkl_sequential -o build/lib.linux-x86_64-3.7/fastlmm/util/matrix/cample.cpython-37m-x86_64-linux-gnu.so
  /usr/bin/ld: cannot find -lmkl_rt
  /usr/bin/ld: cannot find -lmkl_sequential
 collect2: error: ld returned 1 exit status
  error: command 'g++' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for fastlmm
Failed to build fastlmm
ERROR: Could not build wheels for fastlmm which use PEP 517 and cannot be installed directly
```

Best regards
H.

**Comment by snowformatics** [comment]
@Xenokrates 

Answer from the author: 
https://github.com/fastlmm/FaST-LMM/issues/18#issuecomment-863282052

**Comment by Xenokrates** [comment]
@snowformatics: It seems that we need *conda* to get the FaST-LMM package up and running.

Here ist my test setting using a *miniconda* environment in CentOS 7:

````
cd /tmp
# Create conda env with required packages.
conda create -n FaST-LMM mkl==2019.4 scipy numpy
conda activate FaST-LMM
pip install --no-build-isolation fastlmm
git clone https://github.com/snowformatics/gwas_web_production.git
cd gwas_web_production/
vi requirements.txt  ### <- Remove required versions from *numpy* *scipy* *fastlmm*
pip install -r requirements.txt
python main_app.py
````
Output:
````
/tmp/gwas_web_production
 * Serving Flask app "main_app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
/tmp/gwas_web_production
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 261-186-480
INFO:werkzeug:127.0.0.1 - - [17/Jun/2021 17:31:00] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [17/Jun/2021 17:31:00] "GET /static/gwas_banner.png HTTP/1.1" 200 -
````
It's running :-)

Best regards,
H.

**Comment by snowformatics** [comment]
Awsome!
