### ISSUE TITLE
Test with sample data

### ISSUE THREAD

**Issue by snowformatics** [snowformatics/gwas_web_production#2]
Hi @Xenokrates,

could you please try a simple test:

Choose BGT_96hai under "Choose Phenotype" and press submit. Hopefully after some seconds a plot should appear / open inside the browser.

![shot01](https://user-images.githubusercontent.com/5192670/122439394-e8599e80-cf9b-11eb-8f79-1ddaa9df4aa4.PNG)

Thanks!

**Comment by Xenokrates** [comment]
Hi @snowformatics,

test fails. --> 

* No plot window apears.
* During the test an editor opens and blocks the process.
* The errors and warnings you find in the attached files.

Best regards H.
[stdout.log](https://github.com/snowformatics/gwas_web_production/files/6675748/stdout.log)
[stderr.log](https://github.com/snowformatics/gwas_web_production/files/6675750/stderr.log)

**Comment by snowformatics** [comment]
ok,

GWAS analysis is running through, that's good.

Could you please check whether there was a file named out.csv (about 8 MB) created in 
gwas_web_production\data\results

If yes, could you please pull again the repro, try again and check whether there is a html file with the plots created:
gwas_web_production\test.html

Thanks!

**Comment by Xenokrates** [comment]
Both files are there as expected.

* data/results/out.csv (8407010 Byte)
* 8407010 (4240823 Byte)

The process still stops after calculating the results in an editor process, that i have to stop with 'q' -> 'y'
The editor is empty but in the upper right corner I see "Bokeh Plot".

Regards

**Comment by snowformatics** [comment]
Ok, for the moment that's enough, since we will sent the results via mail. 
Great news!
