### ISSUE TITLE
Error "... no encoding declared..."

### ISSUE THREAD

**Issue by Xenokrates** [snowformatics/gwas_web_production#4]
When I run ithe app in a docker container,I get the following error, which terminates the app.

> gwas@4e8cf2c3a308:~/gwas_web_production$ python main_app.py 
>  File "main_app.py", line 114
>SyntaxError: Non-ASCII character '\xe2' in file main_app.py on line 114, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

Regards H.

**Comment by snowformatics** [comment]
Should be fixed with  [54a3ceea72d2bc935c655dd1ddccbf9c636a77bb](https://github.com/snowformatics/gwas_web_production/commit/54a3ceea72d2bc935c655dd1ddccbf9c636a77bb)

**Comment by Xenokrates** [comment]
The problem is fixed.
The project runs in a docker container without errors.

Current Dockerfile:
8< - - -
FROM continuumio/miniconda3:latest
SHELL ["/bin/bash", "-c"]
RUN apt-get update && apt-get upgrade -y  && apt-get install -y g++ && \
    rm -rf /var/lib/apt/lists/* && \
    conda update -y -n base -c defaults conda && \
    useradd -m -u 1000 -s /bin/bash gwas && \
    conda install -y mkl==2019.4 scipy numpy && \
    su -l gwas && \
    cd /home/gwas && \
    conda init bash && \
    source /home/gwas/.bashrc && \
    pip install --no-build-isolation fastlmm && \
    git clone https://github.com/Xenokrates/gwas_web_production.git && \
    cd gwas_web_production/ && \
    chown 1000:1000 data/results && \
    chown -R 1000:1000 ./ && \
    chown 1000:1000 data/uploads && \
    pip install -r requirements.txt

USER 1000
WORKDIR /home/gwas/gwas_web_production
EXPOSE 5000/tcp
ENTRYPOINT [ "/bin/bash", "-l", "-c" ]
CMD ["FLASK_APP=main_app.py /opt/conda/bin/python -m flask run --host=0.0.0.0"]

## Run with 
## > docker run -p 5000:5000 --rm gwas-app
8< - - -

**Comment by Xenokrates** [comment]
I close the issue.
